first-automated-tests
neogeo-technologies/geocontrib pull request #131
Opened 2021-05-04 14:59 UTC by hcharp

Creation of first automated tests with RobotFramework:
- connexion
- creation of a project
- creation of a featuretype
- creation of a feature

2021-05-04 15:46 UTC, sebastiendarocha requested changes

2021-05-04 15:46 UTC, sebastiendarocha commented on docs/end-to-end/test_suite.robot
> +${SUPERUSERPASSWORD}    4uL9jyGqRiddT7X
Remplace le MDP par CHANGE_ME

On ne commit jamais jamais un mdp dans git !!

2021-05-04 15:46 UTC, sebastiendarocha commented on docs/end-to-end/library/GeoDeleteLibrary.py
> +# TODO : il faudrait plutôt supprimer les objets directement depuis la base de données.
Mets ce commentaire dans le ticket Redmine plutôt

2021-05-04 15:46 UTC, sebastiendarocha commented on docs/end-to-end/README.md
> +- Scenarios de tests avec Katalon
Est-ce que tu peux faire un petit tuto Katalon ? Ou donner une bonne ref de tuto ?

2021-05-04 15:46 UTC, sebastiendarocha commented on docs/end-to-end/README.md
> +- Écriture et révision des tests avec RobotFramework
Dit plutôt que la structure ou architecture des tests est faire avec RobotFramework non ?

2021-05-04 15:46 UTC, sebastiendarocha commented on docs/end-to-end/README.md
> +GeoContrib
Dit que c'est une instance, on n'est pas obligé de déployer les 2 sur la même machine.

Dit qu'on a besoin d'un compte admin+staff

2021-05-04 15:46 UTC, sebastiendarocha commented on docs/end-to-end/README.md
> +geocontrib_venv activé
Nan, laisse ça aux autres de décider, recommande l'utilisation d'un environnement virtuelle

2021-05-04 15:46 UTC, sebastiendarocha commented on docs/end-to-end/README.md
> +    - [En cours de développement : GeoJson](#En-cours-de-développement-:-GeoJson)
Supprime la section GeoJSON, ça fait très 90s "Site en construction" qui reste en construction 15 ans ;)

2021-05-04 15:46 UTC, sebastiendarocha commented on docs/end-to-end/README.md
> +- ${SUPERUSERNAME} : attention, dans cette version, l'utilisateur doit avoir les droits d'administration
Ne parle pas de "Cette version", dit juste login d'un administrateur

2021-05-05 07:39 UTC, hcharp commented on docs/end-to-end/test_suite.robot
> +${SUPERUSERPASSWORD}    4uL9jyGqRiddT7X
Shame on me...

2021-05-05 15:21 UTC, sebastiendarocha approved these changes

2021-05-06 10:01 UTC, merged