Anomalie 9498: Afficher le login utilisateur dans la carte de recherche si pas de nom/prénom utilisateur
neogeo-technologies/geocontrib pull request #67
Opened 2020-11-02 15:52 UTC by florentLavelle

2020-11-12 09:21 UTC, sebastiendarocha requested changes

2020-11-12 09:21 UTC, sebastiendarocha commented on geocontrib/static/geocontrib/js/map-util.js
> +      : feature.properties.creator.username ? `Auteur: ${feature.properties.creator.username}` : '';
Hou t'es chaud ! double opérateur ternaire !!

Il ne manque pas la Div dans ton Auteur ?

2020-11-12 09:34 UTC, florentLavelle commented on geocontrib/static/geocontrib/js/map-util.js
> +      : feature.properties.creator.username ? `Auteur: ${feature.properties.creator.username}` : '';
Oui en effet, il manquait la div, mais ça marchait sans.
Je l'ai quand même rajoutée.

2020-12-17 08:31 UTC, sebastiendarocha approved these changes

2020-12-17 08:31 UTC, sebastiendarocha approved these changes

2020-12-17 08:33 UTC, merged